/**
 * NUMERIQ.AI - Knowledge Base: Combinations
 * Interpretations for number pair interactions.
 * All 36 Unique Pair Combinations + Self-Pairs.
 */

import { CombinationMeaning } from "../types";

export const COMBINATIONS: Record<string, CombinationMeaning> = {
  // --- SELF PAIRS ---
  "1-1": {
    numberA: 1, numberB: 1,
    harmonyScore: 80,
    harmonyLabel: 'high',
    combinationName: "The Double Pioneer",
    narrative: "When two 1s come together, there is an explosion of individual power. This combination suggests a soul built for total autonomy and singular leadership. There is a laser-like focus on one's own vision, but a significant risk of becoming intellectually and socially isolated.",
    romantically: "This pair needs absolute mutual respect for each other's independence. It is a high-octane relationship that requires both partners to have their own 'empires' to manage.",
    professionally: "Excellent for the solo founder or the high-level consultant. It indicates someone who is best in a role where they are the ultimate authority.",
    friendship: "Often found between two people who respect each other's strength but don't need constant contact.",
    keySynergies: ["Massive drive", "Absolute clarity", "Rapid decision making"],
    keyFrictions: ["Ego clashes", "Lack of compromise", "Emotional distance"],
    adviceForPair: "Learn to consciously pause and consult with others. Your greatest strength—independence—can also be your greatest blind spot."
  },
  "2-2": {
    numberA: 2, numberB: 2,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Twin Reflections",
    narrative: "Two 2s create a very sensitive and harmonious vibration. It indicates a person completely focused on partnership and emotional connection. However, there is a risk of extreme indecision and a tendency to become overwhelmed by the emotions of others.",
    romantically: "A deeply soulful and affectionate partnership. They are perfectly in tune with each other's needs, but may struggle with practical world challenges.",
    professionally: "Excellent for Counseling or Support roles where empathy is the primary tool.",
    friendship: "A very soft, supportive, and intuitive connection.",
    keySynergies: ["Profound empathy", "Absolute harmony", "Intuitive connection"],
    keyFrictions: ["Extreme sensitivity", "Indecision", "Lack of drive"],
    adviceForPair: "You need to find a 'fire' influence to help you make decisions and move forward."
  },
  "3-3": {
    numberA: 3, numberB: 3,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Creative Explosion",
    narrative: "Double the creativity, double the socializing, and double the scattered energy. It's a joyful but often ungrounded combination that needs significant structure to achieve anything lasting.",
    romantically: "A fun-filled, social, and ever-changing relationship. Never a dull moment, but perhaps a few missed bills.",
    professionally: "Brilliant for creative brainstorming or the early stages of artistic ventures.",
    friendship: "The life and soul of every party—fun, inspiring, and very social.",
    keySynergies: ["Pure joy", "Infinite creativity", "Social magnetism"],
    keyFrictions: ["Total lack of focus", "Procrastination", "Emotional superficiality"],
    adviceForPair: "Hire a '4' to manage your life so you can stay free to create."
  },
  "4-4": {
    numberA: 4, numberB: 4,
    harmonyScore: 80,
    harmonyLabel: 'high',
    combinationName: "The Foundation Stones",
    narrative: "Extremely reliable, disciplined, and rigid. This person can build anything through sheer persistence, but they may become stuck in outdated patterns.",
    romantically: "A very solid and traditional relationship. Built to last, but perhaps lacking in spontaneity.",
    professionally: "Unstoppable in project management or any role requiring meticulous attention to complex systems.",
    friendship: "A steady, reliable connection based on shared responsibility.",
    keySynergies: ["Absolute stability", "Infinite patience", "Thoroughness"],
    keyFrictions: ["Rigidity", "Resistance to change", "Emotional dryness"],
    adviceForPair: "Practice says 'yes' to one spontaneous thing every week."
  },
  "5-5": {
    numberA: 5, numberB: 5,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Double Traveler",
    narrative: "Pure movement. Constant change and freedom. It's a vibration of high energy and adaptability, but carries risk of nervous exhaustion.",
    romantically: "An exciting but potentially temporary partnership. Needs constant variety.",
    professionally: "Excellent for consultants, freelance professionals, and fast-moving industries.",
    friendship: "A high-octane connection full of shared adventures.",
    keySynergies: ["Infinite adaptability", "Freedom", "Rapid learning"],
    keyFrictions: ["Total lack of grounding", "Commitment issues", "Restlessness"],
    adviceForPair: "Find a 'home base' where you can periodically recharge."
  },
  "6-6": {
    numberA: 6, numberB: 6,
    harmonyScore: 95,
    harmonyLabel: 'very high',
    combinationName: "The Universal Heart",
    narrative: "Massive focus on care and nurturing. This pair is the ultimate expression of domestic harmony and service.",
    romantically: "A deeply devoted relationship centered on home and children.",
    professionally: "Ideal for community health, education, and family-run enterprises.",
    friendship: "An incredibly warm and supportive bond.",
    keySynergies: ["Deep nurturing", "Stable love", "Community focus"],
    keyFrictions: ["Smothering", "Ignoring own needs", "Control issues"],
    adviceForPair: "Remember to allow those you love the freedom to make their own mistakes."
  },
  "7-7": {
    numberA: 7, numberB: 7,
    harmonyScore: 70,
    harmonyLabel: 'moderate',
    combinationName: "The Twin Seekers",
    narrative: "Deep silence and specialized interests. A powerful intellectual or spiritual force, but detached from the material world.",
    romantically: "A quiet, soulful partnership based on shared mental landscapes.",
    professionally: "Unstoppable in research or spiritual practice.",
    friendship: "A rare bond between two 'outsiders'.",
    keySynergies: ["Ultimate wisdom", "Spiritual focus", "Intellectual depth"],
    keyFrictions: ["Total isolation", "Social paralysis", "Communication barriers"],
    adviceForPair: "Consciously engage with the outside world together."
  },
  "8-8": {
    numberA: 8, numberB: 8,
    harmonyScore: 50,
    harmonyLabel: 'low',
    combinationName: "The Clash of Titans",
    narrative: "Immense power and ego. This pair can build an empire or destroy everything in a power struggle.",
    romantically: "A high-stakes relationship prone to conflict over status and resources.",
    professionally: "Capable of massive material success if they can share command.",
    friendship: "Respect for strength, but lacking in warmth.",
    keySynergies: ["Global power", "Resource mastery", "Stamina"],
    keyFrictions: ["Ego war", "Karmic weight", "Ruthlessness"],
    adviceForPair: "Ground your ambitions in a selfless mission."
  },
  "9-9": {
    numberA: 9, numberB: 9,
    harmonyScore: 100,
    harmonyLabel: 'very high',
    combinationName: "The Universal Council",
    narrative: "Deeply humanitarian and idealistic. Focused entirely on the world-stage and serving humanity.",
    romantically: "An inspiring, soulful relationship acting as 'world parents'.",
    professionally: "Ideal for international law, global charities, and transformative arts.",
    friendship: "Bonded by shared visions for a better world.",
    keySynergies: ["Massive compassion", "Universal charisma", "High ideals"],
    keyFrictions: ["Ignoring the personal", "Burnout", "Idealistic disappointment"],
    adviceForPair: "Nurture your own inner child as much as you nurture the world."
  },

  // --- UNIQUE PAIRS (ordered A < B) ---
  "1-2": {
    numberA: 1, numberB: 2,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Sun and the Moon",
    narrative: "A perfect balance of drive (1) and sensitivity (2). The initiative of the 1 is softened and supported by the diplomacy of the 2.",
    romantically: "A classic, supportive partnership where both roles are clear and respected.",
    professionally: "The 1 builds the vision, the 2 builds the relationships to sustain it.",
    friendship: "A deep bond based on complementary strengths.",
    keySynergies: ["Balanced action", "Empathetic leadership", "Strategic harmony"],
    keyFrictions: ["1 being too dominant", "2 being too sensitive"],
    adviceForPair: "The 1 must remember to appreciate the 2's quiet contributions."
  },
  "1-3": {
    numberA: 1, numberB: 3,
    harmonyScore: 95,
    harmonyLabel: 'very high',
    combinationName: "The Creative Pioneer",
    narrative: "Initiative (1) meets creativity (3). A highly dynamic and fortunate combination leading to rapid social success.",
    romantically: "Energetic and social relationship full of inspiration.",
    professionally: "Brilliant for marketing, media, and innovation.",
    friendship: "The life of any social circle, full of big ideas.",
    keySynergies: ["Limitless creativity", "Social magnetism", "Fast growth"],
    keyFrictions: ["Lack of grounding", "Procrastination"],
    adviceForPair: "Build a solid structure (a 'map') for your brilliant energy."
  },
  "1-4": {
    numberA: 1, numberB: 4,
    harmonyScore: 60,
    harmonyLabel: 'moderate',
    combinationName: "The Driven Builder",
    narrative: "A hard-working but tense combination. The 1 wants risk, the 4 wants order. Can build tangible results through effort.",
    romantically: "Negotiation between adventure (1) and security (4).",
    professionally: "4 provides structure for 1's ideas, but they may clash over speed.",
    friendship: "A reliable bond based on shared responsibility.",
    keySynergies: ["Manifestation power", "Discipline", "Practicality"],
    keyFrictions: ["Rigidity vs Risk", "Impatience"],
    adviceForPair: "Focus on the end goal—you are a powerful team if you coordinate."
  },
  "1-5": {
    numberA: 1, numberB: 5,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Restless Innovator",
    narrative: "High energy and adaptability. Always looking for the next breakthrough. Restless but progressive.",
    romantically: "Exciting and unpredictable partnership needing a lot of space.",
    professionally: "Excellent for sales, global business, and early-stage innovation.",
    friendship: "Full of travel, new ideas, and intellectual sparks.",
    keySynergies: ["Extreme adaptability", "Bold exploration", "High energy"],
    keyFrictions: ["Commitment issues", "Burnout"],
    adviceForPair: "Balance your need for the 'new' with finishing what you start."
  },
  "1-6": {
    numberA: 1, numberB: 6,
    harmonyScore: 70,
    harmonyLabel: 'moderate',
    combinationName: "The Protective Leader",
    narrative: "Balances self-focus (1) with service (6). Leading by caring for others. Success in community-based leadership.",
    romantically: "Caring but potentially stifling relationship. Independence clashes.",
    professionally: "Successful in healing, education, and domestic industries.",
    friendship: "A loyal bond where the 6 anchors the 1's ambitions.",
    keySynergies: ["Nurturing leadership", "Community focus", "Ethics"],
    keyFrictions: ["Control issues", "Over-responsibility"],
    adviceForPair: "The 1 must learn to accept care, and the 6 to give the 1 space."
  },
  "1-7": {
    numberA: 1, numberB: 7,
    harmonyScore: 80,
    harmonyLabel: 'high',
    combinationName: "The Mastermind",
    narrative: "Intellectually powerful and solitary. Independence (1) meets deep wisdom (7). Extreme focus and depth.",
    romantically: "Private and stimulating partnership valuing 'alone time'.",
    professionally: "Ideal for research, strategy, and analytical work.",
    friendship: "Profound connection based on shared intellectual depths.",
    keySynergies: ["Deep insight", "Unwavering focus", "Authority"],
    keyFrictions: ["Extreme isolation", "Emotional detachment"],
    adviceForPair: "Remember that the world needs your wisdom—don't stay hidden."
  },
  "1-8": {
    numberA: 1, numberB: 8,
    harmonyScore: 50,
    harmonyLabel: 'low',
    combinationName: "The Absolute Authority",
    narrative: "Extreme material power and ego. Authoritative and ambitious, but prone to power struggles.",
    romantically: "Intense relationship where control is a constant negotiation.",
    professionally: "Capable of massive success but subject to intense burnout.",
    friendship: "Mutual respect for achievement, but lacking warmth.",
    keySynergies: ["Manifestation", "Executive authority", "Resilience"],
    keyFrictions: ["Ego war", "Ruthlessness", "Status obsession"],
    adviceForPair: "Cultivate humility and remember that power is for service."
  },
  "1-9": {
    numberA: 1, numberB: 9,
    harmonyScore: 100,
    harmonyLabel: 'very high',
    combinationName: "The Visionary Philanthropist",
    narrative: "Brilliant combination of the beginning (1) and the end (9). Global vision and immense charisma.",
    romantically: "Inspiring partnership supporting each other's highest ideals.",
    professionally: "Ideal for leadership in non-profits and international orgs.",
    friendship: "Magnetic bond based on shared values for a better world.",
    keySynergies: ["Global charisma", "Selfless leadership", "Universal vision"],
    keyFrictions: ["Ignoring personal details", "Emotional intensity"],
    adviceForPair: "Don't forget the small details while saving the world."
  },
  "2-3": {
    numberA: 2, numberB: 3,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Artistic Counselor",
    narrative: "Sensitivity (2) meets creativity (3). Excellent at communication with empathy and bringing beauty.",
    romantically: "Charming and social partnership full of laughter.",
    professionally: "Ideal for marketing, events, and counseling.",
    friendship: "Social and supportive friends always there for each other.",
    keySynergies: ["Empathetic expression", "Social ease", "Warmth"],
    keyFrictions: ["Sensitivity to opinion", "Lack of grounding"],
    adviceForPair: "Ground your beautiful dreams in a solid foundation."
  },
  "2-4": {
    numberA: 2, numberB: 4,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Reliable Anchor",
    narrative: "Stable and supportive. Harmony (2) matched by security and order (4). Excellent for building anything long-term.",
    romantically: "Secure relationship focused on building a 'nest'.",
    professionally: "Perfect team for project management and administration.",
    friendship: "Dependable bond that lasts a lifetime.",
    keySynergies: ["Reliability", "Grounded harmony", "Stability"],
    keyFrictions: ["Rigidity", "Emotional dryness if not mindful"],
    adviceForPair: "Allow room for spontaneity to keep the intuition alive."
  },
  "2-5": {
    numberA: 2, numberB: 5,
    harmonyScore: 60,
    harmonyLabel: 'moderate',
    combinationName: "The Sensitive Traveler",
    narrative: "A mix of sensitivity (2) and a need for change (5). Can be erratic but brings great intuitive adaptability.",
    romantically: "Tense but growing relationship between comfort and change.",
    professionally: "Good for rapid-response roles requiring social grace.",
    friendship: "Dynamic but needing frequent communication to stay stable.",
    keySynergies: ["Rapid empathy", "Versatility", "Social perception"],
    keyFrictions: ["Nervous tension", "Indecision vs Restlessness"],
    adviceForPair: "Establish rituals of connection to handle the speed of change."
  },
  "2-6": {
    numberA: 2, numberB: 6,
    harmonyScore: 95,
    harmonyLabel: 'very high',
    combinationName: "The Nurturing Heart",
    narrative: "Maximum harmony and care. Focused on family and beautiful environments.",
    romantically: "Deeply devoted partnership centered on home life.",
    professionally: "Ideal for healing, education, and domestic service.",
    friendship: "The 'parents' of the group—always caring.",
    keySynergies: ["Compassion", "Domestic bliss", "Service"],
    keyFrictions: ["Over-protectiveness", "Ignoring own needs"],
    adviceForPair: "Set healthy boundaries to prevent emotional burnout."
  },
  "2-7": {
    numberA: 2, numberB: 7,
    harmonyScore: 80,
    harmonyLabel: 'high',
    combinationName: "The Intuitive Seeker",
    narrative: "Subtle and soulful. Receptivity (2) meets analytical depth (7). Powerful inner voice.",
    romantically: "Quiet relationship needing 'unspoken' understanding.",
    professionally: "Excellent for psychology, research, or spiritual work.",
    friendship: "Profound connection based on shared spiritual depths.",
    keySynergies: ["Deep intuition", "Scientific empathy", "Wisdom"],
    keyFrictions: ["Communication barriers", "Isolation"],
    adviceForPair: "Learn to articulate your deep feelings to each other."
  },
  "2-8": {
    numberA: 2, numberB: 8,
    harmonyScore: 70,
    harmonyLabel: 'moderate',
    combinationName: "The Power Balance",
    narrative: "Support (2) meeting material mastery (8). High success if the partnership is balanced.",
    romantically: "Works well if both roles (internal vs external) are respected.",
    professionally: "Capable of amassing wealth and managing large resources.",
    friendship: "Bond based on shared achievement and support.",
    keySynergies: ["Wealth creation", "Stability", "Resource management"],
    keyFrictions: ["Power struggles", "Unappreciation"],
    adviceForPair: "The 8 must express gratitude for the 2's subtle work."
  },
  "2-9": {
    numberA: 2, numberB: 9,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Global Harmonizer",
    narrative: "Universal love (9) meets personal empathy (2). Broad vision focused on personal connections.",
    romantically: "Soulful relationship with a shared humanitarian mission.",
    professionally: "Excellent for diplomatic work and community healing.",
    friendship: "Kind and supportive bond focused on the greater good.",
    keySynergies: ["Wide compassion", "Intuitive connection", "Peacekeeping"],
    keyFrictions: ["Emotional exhaustion", "Idealism"],
    adviceForPair: "Protect your personal energy as you serve the many."
  },
  "3-4": {
    numberA: 3, numberB: 4,
    harmonyScore: 50,
    harmonyLabel: 'low',
    combinationName: "The Creative Foundation",
    narrative: "Conflict between joy/expression (3) and structure/discipline (4). Tension but high manifestation potential.",
    romantically: "Needs constant communication between fun and duty.",
    professionally: "Excellent if they can stay focused; 4 builds what 3 imagines.",
    friendship: "A complementary but often frustrating connection.",
    keySynergies: ["Solid expression", "Ordered creativity", "Manifestation"],
    keyFrictions: ["Rigidity vs Chaos", "Criticism"],
    adviceForPair: "See the 4's structure as the support for the 3's beauty."
  },
  "3-5": {
    numberA: 3, numberB: 5,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Social Catalyst",
    narrative: "Charm (3) meets change (5). Masters of communication, networking, and influence.",
    romantically: "Exhilarating relationship full of adventure and talk.",
    professionally: "Ideal for marketing, media, and consulting.",
    friendship: "Always at the center of the latest trends.",
    keySynergies: ["Infinite variety", "Social mastery", "Persuasion"],
    keyFrictions: ["Restlessness", "Burnout", "Superficiality"],
    adviceForPair: "Learn the power of pausing together."
  },
  "3-6": {
    numberA: 3, numberB: 6,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Artistic Home",
    narrative: "Expression (3) meets responsibility (6). Creating beauty for the family and community.",
    romantically: "Charming, artistic partnership focused on domestic bliss.",
    professionally: "Excellent for teaching, interior design, and catering.",
    friendship: "Warm, social, and very supportive bond.",
    keySynergies: ["Social grace", "Domestic beauty", "Creativity"],
    keyFrictions: ["Over-commitment", "Scattered duty"],
    adviceForPair: "Focus your combined creative energy on one core goal."
  },
  "3-7": {
    numberA: 3, numberB: 7,
    harmonyScore: 60,
    harmonyLabel: 'moderate',
    combinationName: "The Spiritual Storyteller",
    narrative: "Social expansion (3) meets deep introspection (7). A mix of light and shadow.",
    romantically: "Needs balance between social time and quiet time.",
    professionally: "Good for writing about complex or spiritual topics.",
    friendship: "Unique bond between a talker and a listener.",
    keySynergies: ["Informed creativity", "Intellectual charm", "Depth"],
    keyFrictions: ["Social clashes", "Misunderstanding silence"],
    adviceForPair: "The 3 should bring joy to the 7, and the 7 should bring depth to the 3."
  },
  "3-8": {
    numberA: 3, numberB: 8,
    harmonyScore: 70,
    harmonyLabel: 'moderate',
    combinationName: "The Successful Executive",
    narrative: "Expansion (3) combined with material mastery (8). High status through charm and power.",
    romantically: "Dynamic and high-profile relationship focused on success.",
    professionally: "Massive potential in media management or big business.",
    friendship: "Mutual respect for achievement and creative flair.",
    keySynergies: ["Status", "Wealth", "Social influence"],
    keyFrictions: ["Materialism", "Control of the 'stage'"],
    adviceForPair: "Don't let the pursuit of status kill the joy of the 3."
  },
  "3-9": {
    numberA: 3, numberB: 9,
    harmonyScore: 100,
    harmonyLabel: 'very high',
    combinationName: "The Joyful Philanthropist",
    narrative: "Communication (3) and universal love (9). Inspiring others toward a higher mission.",
    romantically: "Soulful and vibrant partnership full of shared ideals.",
    professionally: "Ideal for transformative arts, global teaching, and charity.",
    friendship: "Deeply inspiring bond based on shared visions.",
    keySynergies: ["Universal charisma", "Creativity", "Altruism"],
    keyFrictions: ["Ignoring personal routine", "Emotional intensity"],
    adviceForPair: "Keep one foot on the ground while your heads are in the stars."
  },
  "4-5": {
    numberA: 4, numberB: 5,
    harmonyScore: 40,
    harmonyLabel: 'very low',
    combinationName: "The Bridge Over Chaos",
    narrative: "Stability (4) vs Change (5). Intense tension between order and freedom.",
    romantically: "Difficult relationship requiring massive compromise.",
    professionally: "High conflict, but 4 provides the box that 5 needs to play in.",
    friendship: "Challenging bond based on correcting each other's excesses.",
    keySynergies: ["Adaptable structure", "Controlled change", "Progress"],
    keyFrictions: ["Rigidity vs Recklessness", "Impatience"],
    adviceForPair: "The 4 must allow movement, and the 5 must respect the center."
  },
  "4-6": {
    numberA: 4, numberB: 6,
    harmonyScore: 95,
    harmonyLabel: 'very high',
    combinationName: "The Loyal Guardian",
    narrative: "Structure (4) and care (6). Absolute foundation of love and responsibility.",
    romantically: "One of the most stable partnerships; built for the long haul.",
    professionally: "Perfect for administrative leadership in caring industries.",
    friendship: "The 'family' anchor of the friend group.",
    keySynergies: ["Reliability", "Nurturing foundations", "Integrity"],
    keyFrictions: ["Resistance to change", "Over-responsibility"],
    adviceForPair: "Allow yourselves to play occasionally—not everything is a duty."
  },
  "4-7": {
    numberA: 4, numberB: 7,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Scientific Mind",
    narrative: "Logic (4) meets internal wisdom (7). Extremely thorough and analytical.",
    romantically: "Quiet, intellectual partnership based on mutual respect.",
    professionally: "Unstoppable in research, engineering, and specialized study.",
    friendship: "Serious bond built on deep, structured conversations.",
    keySynergies: ["Analytical depth", "Scientific focus", "Methodical wisdom"],
    keyFrictions: ["Social isolation", "Dryness", "Rigidity"],
    adviceForPair: "Invite some 'fire' (3, 5) into your life to keep things from getting too dry."
  },
  "4-8": {
    numberA: 4, numberB: 8,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Master Architect",
    narrative: "Discipline (4) meets material power (8). The ability to build grand, lasting systems.",
    romantically: "A powerful, status-oriented relationship with deep common goals.",
    professionally: "Ideal for large-scale construction, finance, or corporate structure.",
    friendship: "Built on mutual respect for competence and achievement.",
    keySynergies: ["Manifestation power", "Stamina", "System building"],
    keyFrictions: ["Workaholism", "Lack of emotion", "Power focus"],
    adviceForPair: "Remember that you are humans first, builders second."
  },
  "4-9": {
    numberA: 4, numberB: 9,
    harmonyScore: 60,
    harmonyLabel: 'moderate',
    combinationName: "The Structured Idealist",
    narrative: "The 4's focus on the local meets the 9's focus on the global. Practicality vs Idealism.",
    romantically: "Needs balance between the routine and the world-mission.",
    professionally: "Excellent for putting humanitarian ideas into practical form.",
    friendship: "A bond based on shared integrity and work ethic.",
    keySynergies: ["Practical altruism", "Grounded vision", "Reliability"],
    keyFrictions: ["Scale clashes", "Frustration with idealism"],
    adviceForPair: "The 4 provides the means, the 9 provides the meaning."
  },
  "5-6": {
    numberA: 5, numberB: 6,
    harmonyScore: 70,
    harmonyLabel: 'moderate',
    combinationName: "The Compassionate Traveler",
    narrative: "Freedom (5) meeting responsibility (6). Balances adventure with home.",
    romantically: "Needs negotiation between domestic duty and the need for space.",
    professionally: "Good for sales in domestic fields or community events.",
    friendship: "A warm bond that allows for frequent absence.",
    keySynergies: ["Adaptable care", "Social empathy", "Variety"],
    keyFrictions: ["Commitment vs Duty", "Restlessness in the home"],
    adviceForPair: "Find a way to travel together to satisfy both needs."
  },
  "5-7": {
    numberA: 5, numberB: 7,
    harmonyScore: 85,
    harmonyLabel: 'high',
    combinationName: "The Explorer of Mysteries",
    narrative: "Physical exploration (5) and mental exploration (7). A highly intellectual and free-thinking pair.",
    romantically: "Stimulating but potentially distant. Needs shared intellectual interests.",
    professionally: "Brilliant for field research and philosophical inquiry.",
    friendship: "Deep conversations in unusual places.",
    keySynergies: ["Deep insight", "Freedom of thought", "Rapid learning"],
    keyFrictions: ["Lack of grounding", "Isolation", "Commitment"],
    adviceForPair: "Ground your deep discoveries in something tangible."
  },
  "5-8": {
    numberA: 5, numberB: 8,
    harmonyScore: 75,
    harmonyLabel: 'high',
    combinationName: "The Strategic Adventurer",
    narrative: "Change (5) and power (8). Rapid expansion and material success through risk.",
    romantically: "High-energy, status-oriented relationship. Very social.",
    professionally: "Excellent for venture capital, global business, and fast-paced trades.",
    friendship: "Respect for each other's drive and adaptability.",
    keySynergies: ["Calculated risk", "Fast wealth", "Adaptability"],
    keyFrictions: ["Ruthlessness", "Stability issues", "High pressure"],
    adviceForPair: "Create a stable fallback plan for your rapid expansions."
  },
  "5-9": {
    numberA: 5, numberB: 9,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Global Messenger",
    narrative: "Adaptability (5) and universal vision (9). Bringing new ideas to the world.",
    romantically: "Inspirational relationship full of travel and shared ideals.",
    professionally: "Ideal for international media, non-profits, and the global arts.",
    friendship: "A magnetic bond based on shared freedom and compassion.",
    keySynergies: ["Wide influence", "Adaptability", "Charisma"],
    keyFrictions: ["Ignoring the local", "Lack of grounding", "Burnout"],
    adviceForPair: "Take care of your personal health as much as the world's vision."
  },
  "6-7": {
    numberA: 6, numberB: 7,
    harmonyScore: 65,
    harmonyLabel: 'moderate',
    combinationName: "The Wise Counselor",
    narrative: "Service/Care (6) meets silence/wisdom (7). Refined and empathetic, but potentially quiet.",
    romantically: "Quiet, soulful relationship focused on home and inner truth.",
    professionally: "Good for psychology, education, and specialized healing.",
    friendship: "A quiet, profound connection based on mutual respect.",
    keySynergies: ["Grounded wisdom", "Scientific care", "Refinement"],
    keyFrictions: ["Communication barriers", "Isolation", "Emotional distance"],
    adviceForPair: "Learn to share your inner worlds to keep the heart open."
  },
  "6-8": {
    numberA: 6, numberB: 8,
    harmonyScore: 95,
    harmonyLabel: 'very high',
    combinationName: "The Master of the Home",
    narrative: "Responsibility (6) and material mastery (8). Building a family empire.",
    romantically: "Very successful and stable pairing focused on building for the legacy.",
    professionally: "Perfect for large-scale family businesses or philanthropic leadership.",
    friendship: "Built on shared duty and material achievement.",
    keySynergies: ["Massive stability", "Resource stewardship", "Protection"],
    keyFrictions: ["Power focus", "Workaholism", "Status obsession"],
    adviceForPair: "Ensure the children/employees feel loved, not just provided for."
  },
  "6-9": {
    numberA: 6, numberB: 9,
    harmonyScore: 100,
    harmonyLabel: 'very high',
    combinationName: "The Humanitarian Guardian",
    narrative: "Love for the many (9) and love for the few (6). Maximum compassion and service.",
    romantically: "Intensely soulful and devoted relationship. The 'Perfect Pair' for service.",
    professionally: "Ideal for large-scale charity, healing, and community leadership.",
    friendship: "Deeply supportive and inspiring bond.",
    keySynergies: ["Limitless care", "Universal love", "Charisma"],
    keyFrictions: ["Over-responsibility", "Emotional exhaustion"],
    adviceForPair: "Set boundaries so you don't burn out together."
  },
  "7-8": {
    numberA: 7, numberB: 8,
    harmonyScore: 60,
    harmonyLabel: 'moderate',
    combinationName: "The Strategic Seeker",
    narrative: "Wisdom (7) and material power (8). Can build high-level systems with deep integrity.",
    romantically: "Private, status-oriented relationship based on respect for competence.",
    professionally: "Powerful in finance, research management, and long-term strategy.",
    friendship: "Serious bond built on shared intellectual and material goals.",
    keySynergies: ["Analytical power", "Executive wisdom", "Stamina"],
    keyFrictions: ["Dryness", "Lack of social warmth", "Power struggles"],
    adviceForPair: "Focus on the spiritual purpose of your material power."
  },
  "7-9": {
    numberA: 7, numberB: 9,
    harmonyScore: 90,
    harmonyLabel: 'very high',
    combinationName: "The Prophet",
    narrative: "Wisdom (7) meets universal love (9). A powerfully spiritual and intuitive pairing.",
    romantically: "Profoundly soulful and quiet relationship focused on the higher planes.",
    professionally: "Ideal for spiritual teaching, philosophy, and the visionary arts.",
    friendship: "Rare bond between two people who see 'through' the material world.",
    keySynergies: ["Prophetic insight", "Spiritual charisma", "Wisdom"],
    keyFrictions: ["Social isolation", "Impracticality", "Intensity"],
    adviceForPair: "Build simple, grounded routines to handle the physical world."
  },
  "8-9": {
    numberA: 8, numberB: 9,
    harmonyScore: 70,
    harmonyLabel: 'moderate',
    combinationName: "The Global Sovereign",
    narrative: "Material power (8) meets universal vision (9). Power and compassion in high-stakes settings.",
    romantically: "Intense relationship that can be high-profile and mission-driven.",
    professionally: "Excellent for large scale non-profits and ethical business leadership.",
    friendship: "Respect for scale and vision.",
    keySynergies: ["Global scale", "Manifestation stamina", "Charisma"],
    keyFrictions: ["Ego vs Idealism", "Karmic weight", "Burnout"],
    adviceForPair: "Keep the 8's discipline focused on the 9's humanitarian heart."
  }
};
