/**
 * NUMERIQ.AI — Cheiro's Book of Numbers (Pure Edition) & Sepharial's Kabala of Numbers
 * Traditional Chaldean and Kabalistic Single Number Interpretations (1-9).
 */

import { NumberKnowledge, NumberQuality, LuckyColor } from "../types";

export const NUMBER_KNOWLEDGE: Record<number, NumberKnowledge> = {
  1: {
    number: 1,
    name: "The Pioneer",
    planet: "Sun",
    vibration: "Creative, Individual, Positive",
    quality: "favorable",
    qualityExplanation: "The number of the Sun, representing the king, the father, and the beginning of all things.",
    coreMeaning: "The 1 vibration represents original action and the initiating basis of all other numbers. It is a frequency of absolute creation, leadership, and stubborn independence.",
    asDestinyNumber: "Your destiny is to lead, innovate, and stand alone if necessary. You are a pioneer meant to initiate new starts.",
    asLifePath: "Your path is one of self-realization and individual achievement. You must learn to lead without being tyrannical.",
    asSoulUrge: "Driven by a soul-deep desire to be a forerunner and a survivor. The inner engine is tightly bound to natural instincts and the ego.",
    asPersonality: "Presents an image of personal power and creative leadership. Often seen as an ambitious trailblazer.",
    asBirthDay: "Born to initiate. You possess the raw power to manifest your will.",
    strengths: ["Ambitious", "Determined", "Creative", "Individualistic"],
    challenges: ["Obstinate", "Egotistical", "Dislikes restraint"],
    hiddenStrengths: ["Inventive original nature", "Generosity when respected"],
    careerPaths: ["Founder", "Leader", "Inventor", "Executive"],
    careerNarrative: "Always rises to positions of authority. Best suited for roles where they can organize and control their surroundings.",
    relationshipPattern: "Being in love and being loved is as vital a necessity to them as the very air they breathe. The Number 1 person resents famil- iarity from strangers, but is extremely warm and affectionate with those who are loved and trusted.",
    financialPattern: "Successful through individual effort and bold ventures.",
    healthPattern: "High vitality but prone to stress-related heart and eye issues.",
    compatibleWith: [1, 4, 7, 9],
    challengingWith: [6, 8],
    neutralWith: [2, 3, 5],
    luckyColors: [{ name: "Gold", hex: "#FFD700", reason: "Sun vibration" }, { name: "Yellow", hex: "#FFFF00", reason: "Vitality" }],
    luckyDays: ["Sunday", "Monday"],
    luckyGems: ["Ruby", "Amber", "Golden Topaz"],
    luckyNumbers: [1, 10, 19, 28],
    missingMeaning: "Lack of initiative or self-confidence; difficulty asserting one's own will.",
    missingImpact: { relationships: "May follow others too much", career: "Difficulty starting new projects", finances: "Passivity in wealth building", dailyLife: "Lack of focus" },
    missingRemedy: { color: "Orange", habit: "Morning affirmations", name: "Change to a 1 vibration", element: "Fire", timing: "Dawn" },
    isGoodNumber: true,
    indaNarrative: "The Number 1 vibrates to the Sun. It represents creativity, pro- tection, and benevolence. 1 is the number of original action, the ini- A person or entity is influenced by the Number 1 if born on the 1st, 10th, 19th, or 28th day of any month in any year. People or",
    historicalNote: "Traced to ancient Chaldean sources; Sepharial notes that the earliest enumeration was made from these sources, which were distinctly decimal.",
    sunSignInteractions: {
      "Leo": "Intensifies Sun Sign traits.",
      "Aquarius": "Opposes Sun Sign motives; requires effort to balance.",
      "Aries": "Harmonizes well."
    },
    element: "Fire"
  },
  2: {
    number: 2,
    name: "The Diplomat",
    planet: "Moon",
    vibration: "Gentle, Imaginative, Artistic",
    quality: "neutral",
    qualityExplanation: "The number of the Moon, representing the mother, the creative imagination, and the fluctuating nature of emotions.",
    coreMeaning: "The 2 vibration represents the feminine principle, sensitivity, and intuition. It is a frequency of cooperation, peacemaking, and psychic openness.",
    asDestinyNumber: "Your destiny is to be a supportive companion, a diplomat, and a peacemaker. You thrive in partnership.",
    asLifePath: "Your path involves learning cooperation and handling sensitivity. You must develop emotional stability and trust your intuition.",
    asSoulUrge: "Thirsts for physical intimacy, reassurance, and emotional closeness. The soul seeks to be part of a complementary duo.",
    asPersonality: "Appears as a tactful, friendly, and helpful peacemaker. Projecting a gentle and diplomatic persona.",
    asBirthDay: "Gifted with sensitivity and the ability to understand others deeply.",
    strengths: ["Gentle", "Romantic", "Inventive", "Tactful"],
    challenges: ["Oversensitive", "Easily despondent", "Indecisive"],
    hiddenStrengths: ["Secretly psychic", "Highly developed intuition"],
    careerPaths: ["Mediator", "Artist", "Counselor", "Caregiver"],
    careerNarrative: "Performs best in supportive roles or creative environments where discord is absent.",
    relationshipPattern: "' A 2 person fears every conceivable kind of loss: loss of love, property, money, friendship, employment — loss of loved ones through death or any other kind of separation. These people need a home base, and although they adore to travel the globe as frequently as finances per- mit, they must have a home to return to. In no way can a 2 person be a 'soldier of fortune,' to whom home is where you hang your hat. They make ideal parents themselves, but they must be careful not to smother their children with possessive love. They love money, but like to accumulate it in a safe, stable way, then invest it securely, so it can increase through dividends and interest.",
    financialPattern: "Fluctuating; better at managing others' wealth than creating their own through force.",
    healthPattern: "Prone to digestive issues and emotional stress.",
    compatibleWith: [2, 7, 9],
    challengingWith: [1, 8, 9],
    neutralWith: [3, 4, 5, 6],
    luckyColors: [{ name: "Green", hex: "#008000", reason: "Life/Growth" }, { name: "Cream", hex: "#FFFDD0", reason: "Moon resonance" }],
    luckyDays: ["Monday", "Friday", "Sunday"],
    luckyGems: ["Pearl", "Moonstone", "Jade"],
    luckyNumbers: [2, 11, 20, 29],
    missingMeaning: "Difficulty connecting with others; lack of empathy or emotional awareness.",
    missingImpact: { relationships: "Insensitivity", career: "Poor teamwork", finances: "Lack of intuition in deals", dailyLife: "Emotional dryness" },
    missingRemedy: { color: "Pale Blue", habit: "Journaling feelings", name: "Add a 2 vibration", element: "Water", timing: "Late evening" },
    isGoodNumber: true,
    indaNarrative: "The Number 2 vibrates to the Moon. It represents imagination, parenthood, and sensitivity. 2 is the number of conception, child- A person or entity is influenced by the Number 2 if born on the 2nd, 11th, 20th, or 29th day of any month, in any year. People or",
    historicalNote: "Associated with the Dual Nature in ancient Chaldean thought—representing the reflective side of life.",
    sunSignInteractions: {
      "Cancer": "Intensifies Sun Sign traits.",
      "Capricorn": "Opposes Sun Sign motives; requires effort to balance."
    },
    element: "Water"
  },
  3: {
    number: 3,
    name: "The Counselor",
    planet: "Jupiter",
    vibration: "Ambitious, Disciplined, Authoritative",
    quality: "favorable",
    qualityExplanation: "The number of Jupiter, representing expansion, logic, and the mastery of a profession.",
    coreMeaning: "The 3 vibration is the frequency of self-discipline, order, and ambition. It represents the foundation of a great ideal and the drive for high truth.",
    asDestinyNumber: "Your destiny is to teach, advise, and rise to authority through discipline and knowledge.",
    asLifePath: "Your path is one of expansion and authority. You must learn to handle power without becoming overly dictatorial.",
    asSoulUrge: "Internally driven by a constant state of mental activity and the pursuit of 'rebirth'. The soul is always thinking of the future.",
    asPersonality: "Projects an energetic, positive, and creative aura. Often seen as lucky and charismatic.",
    asBirthDay: "Natural authority and ability to learn quickly. Success through knowledge.",
    strengths: ["Disciplined", "Independent", "Ambitious", "Orderly"],
    challenges: ["Dictatorial", "Fiercely proud", "Dislikes being under others"],
    hiddenStrengths: ["Bubbling contagious optimism", "Philosophical wisdom"],
    careerPaths: ["Teacher", "Judge", "Military Leader", "Public Speaker"],
    careerNarrative: "Often rise to the highest positions in government or organizations. Excellent in execution of commands.",
    relationshipPattern: "They aim high for truth, and nothing less than truth will satisfy them, whether they seek the truth of a love affair, a friendship, a career, politics, or religion. There's a genuine love for animals and a strong tendency to defend the underdog human with the same loyalty they show to their dogs, horses, and other pets. There's a marked indifference to family ties, and marriage works only when freedom is total.",
    financialPattern: "Prosperous through professional mastery and high positions.",
    healthPattern: "Prone to overwork and skin issues.",
    compatibleWith: [3, 6, 9],
    challengingWith: [5, 8],
    neutralWith: [1, 2, 4, 7],
    luckyColors: [{ name: "Purple", hex: "#800080", reason: "Authority" }, { name: "Violet", hex: "#EE82EE", reason: "Spirituality" }],
    luckyDays: ["Thursday", "Friday", "Tuesday"],
    luckyGems: ["Amethyst"],
    luckyNumbers: [3, 12, 21, 30],
    missingMeaning: "Lack of discipline or direction; difficulty finishing what is started.",
    missingImpact: { relationships: "Lack of growth together", career: "Stagnation", finances: "Poor planning", dailyLife: "Disarray" },
    missingRemedy: { color: "Magenta", habit: "Setting 5-year goals", name: "Add a 3 vibration", element: "Air", timing: "Late morning" },
    isGoodNumber: true,
    indaNarrative: "The Number 3 vibrates to the planet Jupiter. It represents idealism, higher education, foreign travel, and religion. 3 is the num- ber of optimism, movement, expansion — and the Holy Trinity of the A person or entity is influenced by the Number 3 if born on the",
    historicalNote: "The first number of the 'Common Numbers' group in Chaldean science. Represents the power of the Trinity.",
    sunSignInteractions: {
      "Sagittarius": "Intensifies Sun Sign traits.",
      "Gemini": "Opposes Sun Sign motives; requires effort to balance."
    },
    element: "Air"
  },
  4: {
    number: 4,
    name: "The Individualist",
    planet: "Uranus",
    vibration: "Unconventional, Rebellious, Stable",
    quality: "challenging",
    qualityExplanation: "The number of Uranus (Sun's shadow). Represents the eccentric, the unconventional, and the sudden changes of fate.",
    coreMeaning: "The 4 vibration is the frequency of the rebel and the underdog. It represents stability through struggle and the ability to see the world differently from the majority.",
    asDestinyNumber: "Your destiny is to change existing patterns and advocate for the unusual. You often find yourself in opposition.",
    asLifePath: "Your path involves learning to handle sudden changes and social isolation. You are here to build firm foundations on unconventional ideas.",
    asSoulUrge: "Driven by a need to be different and to stand for the truth as you see it, regardless of popularity.",
    asPersonality: "Appears unconventional and perhaps a bit stubborn. Seen as someone who doesn't quite fit the 'usual' mold.",
    asBirthDay: "Born with the power to see through social conventions. Natural ability to organize and build.",
    strengths: ["Practical", "Unconventional", "Reliable", "Strong-willed"],
    challenges: ["Stubborn", "Rebellious", "Feels isolated"],
    hiddenStrengths: ["Ability to see 'the other side'", "Unique organizational skills"],
    careerPaths: ["Engineer", "Reformer", "Statistician", "Scientist"],
    careerNarrative: "Often finds success in technical or avant-garde fields where their unique perspective is an asset.",
    relationshipPattern: "4 people are seldom understood by their friends and family.",
    financialPattern: "Inconsistent; gains and losses come in sudden waves.",
    healthPattern: "Prone to 'mysterious' illnesses that are difficult to diagnose.",
    compatibleWith: [1, 4, 8],
    challengingWith: [5, 6, 7],
    neutralWith: [2, 3, 9],
    luckyColors: [{ name: "Grey", hex: "#808080", reason: "Stability" }, { name: "Electric Blue", hex: "#7DF9FF", reason: "Uranus resonance" }],
    luckyDays: ["Saturday", "Sunday", "Monday"],
    luckyGems: ["Sapphire", "Hessonite"],
    luckyNumbers: [4, 13, 22, 31],
    missingMeaning: "Lack of structure or practicality; difficulty staying grounded.",
    missingImpact: { relationships: "Unreliability", career: "Poor organization", finances: "Wastefulness", dailyLife: "Chaos" },
    missingRemedy: { color: "Brown", habit: "Budgeting", name: "Add a 4 vibration", element: "Earth", timing: "Midnight" },
    isGoodNumber: false,
    remedyIfChallenging: "Avoid double 4/8 combinations; take important actions on 1st or 6th dates.",
    indaNarrative: "The Number 4 vibrates to the planet Uranus. It represents indi- vidualism, originality, inventiveness, and tolerance. 4 is the number of unconventional behavior and sudden, unexpected events — also of A person or entity is influenced by the Number 4 if born on the",
    historicalNote: "Anciently linked to the North Node (Rahu) and the planet Uranus. Known as the 'shadow of the Sun'.",
    sunSignInteractions: {
      "Aquarius": "Intensifies Sun Sign traits.",
      "Leo": "Opposes Sun Sign motives; requires effort to balance."
    },
    element: "Earth"
  },
  5: {
    number: 5,
    name: "The Messenger",
    planet: "Mercury",
    asSoulUrge: "Motivated by an intense yearning for freedom, change, and the exploration of all senses. The soul loathes routine and is constantly seeking the thrill of the new and the adventurous.",
    asPersonality: "Projects a charming, sensual, and highly adaptable image. Seen as a versatile communicator who can attract media attention and potentially fame; always independent and quick-moving.",
    indaNarrative: "The number 5 vibrates to the planet Mercury. It represents com- munication, movement, and versatility. It's the number of the intel- A person or entity is influenced by the number 5 if born on the 5th, 14th, or 23rd day of any month in any year. People born on the",
    sunSignInteractions: {
      "Gemini": "Intensifies Sun Sign traits.",
      "Virgo": "Intensifies Sun Sign traits.",
      "Sagittarius": "Opposes Sun Sign motives; requires effort to balance.",
      "Pisces": "Opposes Sun Sign motives; requires effort to balance.",
      "Aries": "Mingles/Harmonizes depending on mood.",
      "Taurus": "Mingles/Harmonizes depending on mood.",
      "Cancer": "Mingles/Harmonizes depending on mood.",
      "Leo": "Mingles/Harmonizes depending on mood.",
      "Libra": "Mingles/Harmonizes depending on mood.",
      "Scorpio": "Mingles/Harmonizes depending on mood.",
      "Capricorn": "Mingles/Harmonizes depending on mood.",
      "Aquarius": "Mingles/Harmonizes depending on mood."
    }
  },
  6: {
    number: 6,
    name: "The Lover",
    planet: "Venus",
    vibration: "Magnetic, Compassionate, Harmonious",
    quality: "favorable",
    qualityExplanation: "The number of Venus, representing love, beauty, harmony, and the domestic sphere.",
    coreMeaning: "The 6 vibration is the frequency of magnetic attraction and genuine devotion. It represents the peace-loving nature and the constant search for harmony in all environments.",
    asDestinyNumber: "Your destiny is to create harmony, provide care, and manifest beauty. You thrive in the home and community.",
    asLifePath: "Your path involves learning responsibility and creating a safe harbor for others. You must balance the need for luxury with genuine service.",
    asSoulUrge: "The heart seeks a safe harbor and 'domestic bliss'. Deeply devoted to the family fold.",
    asPersonality: "Appears as a magnetic and harmonious individual who appreciates beauty in all forms. Seen as a responsible provider.",
    asBirthDay: "Gifted with charm and a natural eye for aesthetics. Success through personal charisma.",
    strengths: ["Magnetic", "Compassionate", "Artistic", "Determined"],
    challenges: ["Stubborn", "Abhors discord", "Can be extravagant"],
    hiddenStrengths: ["Ability to manifest money through charm", "Deep connection to Nature"],
    careerPaths: ["Designer", "Chef", "Home Maker", "Musician", "Florist"],
    careerNarrative: "Thrives in tranquil environments where they can work with beautiful things or care for others.",
    relationshipPattern: "6 is the number of love and romance. They're genuinely loved by their friends and associates — and when they become attached themselves, they're devoted to the loved one. There's more idealism and affection than sensualism in the love na- ture. The 6 vibration -- 302 of 676 -- WHILE THE SOUL SLUMBERS * 239 brings a love of art and a deep affinity for music. These people love nice homes and tasteful furnishings, pastel colors, and harmony in their surroundings.",
    financialPattern: "Prosperous; money often comes without supreme effort, but they oscillate between saving and spending.",
    healthPattern: "Sensitive throat and lungs; needs fresh air and beautiful surroundings.",
    compatibleWith: [3, 6, 9],
    challengingWith: [1, 2, 8],
    neutralWith: [4, 5, 7],
    luckyColors: [{ name: "Rose", hex: "#FF007F", reason: "Love" }, { name: "Blue", hex: "#0000FF", reason: "Harmony" }],
    luckyDays: ["Friday", "Thursday", "Tuesday"],
    luckyGems: ["Turquoise", "Emerald"],
    luckyNumbers: [6, 15, 24],
    missingMeaning: "Lack of harmony in relationships; difficulty expressing love or taking responsibility.",
    missingImpact: { relationships: "Distance", career: "Lack of cooperation", finances: "Poor aesthetic judgment", dailyLife: "Disorder" },
    missingRemedy: { color: "Pink", habit: "Daily acts of service", name: "Add a 6 vibration", element: "Earth", timing: "Twilight" },
    isGoodNumber: true,
    indaNarrative: "The Number 6 vibrates to the planet Venus. It represents the feminine essence, compassion, and (until Venus gives up her rulership of Taurus when the planet Pan-Horus is discovered) also money. 6 is A person or an entity is influenced by the Number 6 if born on",
    historicalNote: "The number of creation (6 days). Associated with Venus and the 'House of Love' in ancient Kabalistic science.",
    sunSignInteractions: {
      "Aquarius": "Intensifies Sun Sign traits.",
      "Taurus": "Intensifies Sun Sign traits.",
      "Libra": "Intensifies Sun Sign traits."
    },
    element: "Earth"
  },
  7: {
    number: 7,
    name: "The Seeker",
    planet: "Neptune",
    vibration: "Independent, Philosophical, Restless",
    quality: "neutral",
    qualityExplanation: "The number of Neptune, representing the occult, mysteries, travel, and the unconventional mind.",
    coreMeaning: "The 7 vibration is the frequency of the seeker and the dreamer. it represents the urge to analyze the unseen world and the longing for distant shores, whether physical or mental.",
    asDestinyNumber: "Your destiny is to probe the mysteries of life, travel, and share philosophical insights.",
    asLifePath: "Your path involves learning to balance restlessness with financial security. You must trust your unique intuition over orthodox views.",
    asSoulUrge: "Inner life is dedicated to investigating the mysterious and the 'occult'. Constantly analyzing and dissecting information.",
    asPersonality: "Presents a reserved, dignified, and highly intelligent image. Often viewed as a respected student.",
    asBirthDay: "Strong leaning towards occultism and intuition. Gifted with original ideas.",
    strengths: ["Independent", "Philosophical", "Original", "Intuitive"],
    challenges: ["Restless", "Indifferent to material", "Private"],
    hiddenStrengths: ["Quiet calming magnetism", "Remarkable dream life"],
    careerPaths: ["Researcher", "Traveler", "Writer", "Astrologer", "Sea Trader"],
    careerNarrative: "Performs best in roles that allow for self-expression and investigation of the unusual.",
    relationshipPattern: "Very private; avoids prying. Needs a partner who respects their need for solitude and travel.",
    financialPattern: "Inconsistent; cares little for wealth but needs a 'rock' of security to stay calm.",
    healthPattern: "Prone to nervous anxiety; needs proximity to water (sea, lake).",
    compatibleWith: [2, 7],
    challengingWith: [4, 8],
    neutralWith: [1, 3, 5, 6, 9],
    luckyColors: [{ name: "Pale Green", hex: "#98FB98", reason: "Neptune resonance" }, { name: "White", hex: "#FFFFFF", reason: "Clarity" }],
    luckyDays: ["Monday", "Sunday"],
    luckyGems: ["Moonstone", "Cat's Eye", "Tiger's Eye"],
    luckyNumbers: [7, 16, 25],
    missingMeaning: "Lack of depth or spiritual awareness; difficulty being alone.",
    missingImpact: { relationships: "Superficiality", career: "Lack of insight", finances: "Poor forecasting", dailyLife: "Restlessness" },
    missingRemedy: { color: "Sea Green", habit: "Weekly meditation", name: "Add a 7 vibration", element: "Water", timing: "Full moon" },
    isGoodNumber: true,
    indaNarrative: "The Number 7 vibrates to the planet Neptune. It represents spir- ituality, sensitivity, sympathy, and mystery 7 is the number of illu- sion and delusion, sometimes deception — but also the number of healing and miracles, faith — and dreams that come true.",
    historicalNote: "A sacred number in all ancient religions. Associated with Neptune and the seven days of the week.",
    sunSignInteractions: {
      "Pisces": "Intensifies Sun Sign traits.",
      "Virgo": "Opposes Sun Sign motives; requires effort to balance."
    },
    element: "Water"
  },
  8: {
    number: 8,
    name: "The Powerhouse",
    planet: "Saturn",
    vibration: "Fatalistic, Intense, Misunderstood",
    quality: "challenging",
    qualityExplanation: "The number of Saturn, representing the 'Taskmaster', material success through struggle, and the weight of responsibility.",
    coreMeaning: "The 8 vibration is the frequency of intensity and fate. It represents the solitary climb to the top, where the soul must balance its vast inner drive with the lessons of the material world.",
    asDestinyNumber: "Your destiny is one of high achievement or major setbacks. You are meant for authority and status through discipline.",
    asLifePath: "Your path is paved with responsibility and heavy authority. You must learn to use power wisely and avoid being misunderstood by being more expressive.",
    asSoulUrge: "Beneath a mask of power lies a highly complex and shy soul. The inner self fears loss of control.",
    asPersonality: "Projects an image of authority, status, and dominant control. Seen as a strict but impeccable leader.",
    asBirthDay: "Deep and intense nature with great strength of individuality. Born for leadership.",
    strengths: ["Intense", "Reliable", "Authoritative", "Durable"],
    challenges: ["Misunderstood", "Fatalistic", "Solitary", "Shy"],
    hiddenStrengths: ["Growing younger with age", "Unshakable sense of duty"],
    careerPaths: ["Politician", "CEO", "Financier", "Judge", "Administrator"],
    careerNarrative: "Excels in roles with maximum responsibility. Reliable as a 'grandfather clock', they work tirelessly for their cause.",
    relationshipPattern: "Although 8 people appear to be cold and undemonstrative with those they love and trust, they can be shyly affectionate and warmly devoted. They're often lonely, needing desperately to be loved, and they're capable of great sacrifices for an ideal, an ambition, or for those who depend on them.",
    financialPattern: "Either great successes or great failures; no happy medium. Material mastery is a core focus.",
    healthPattern: "Prone to issues with teeth, joints, and chronic fatigue.",
    compatibleWith: [2, 4, 8],
    challengingWith: [1, 5, 7, 9],
    neutralWith: [3, 6],
    luckyColors: [{ name: "Dark Grey", hex: "#414742", reason: "Saturnian discipline" }, { name: "Black", hex: "#000000", reason: "Depth" }],
    luckyDays: ["Saturday", "Sunday", "Monday"],
    luckyGems: ["Sapphire", "Amethyst", "Lapis Lazuli"],
    luckyNumbers: [8, 17, 26],
    missingMeaning: "Lack of discipline or ambition; difficulty handling authority or money.",
    missingImpact: { relationships: "Lack of commitment", career: "Poor management", finances: "Irresponsibility", dailyLife: "Weakness" },
    missingRemedy: { color: "Indigo", habit: "Weight training", name: "Add an 8 vibration", element: "Earth", timing: "Dusk" },
    isGoodNumber: false,
    remedyIfChallenging: "Avoid double 8/4 combinations; use the 24th or 6th for important signatures.",
    indaNarrative: ". The Number 8 vibrates to the planet Saturn. It represents wis- dom, learning through experience, stability, patience, and responsibil- ity. 8 is also the number of financial security, caution, restriction, self- A person or entity is influenced by the Number 8 if born on the",
    historicalNote: "Commonly known as the number of Fate. In many ancient cultures, it was avoided for signatures but used for building.",
    sunSignInteractions: {
      "Capricorn": "Intensifies Sun Sign traits.",
      "Cancer": "Opposes Sun Sign motives; requires effort to balance."
    },
    element: "Earth"
  },
  9: {
    number: 9,
    name: "The Warrior",
    planet: "Mars",
    vibration: "Courageous, Forceful, Impulsive",
    quality: "powerful",
    qualityExplanation: "The number of Mars, representing the warrior, the ending of a cycle, and the total of all numbers (infinity).",
    coreMeaning: "The 9 vibration is the frequency of raw courage and completion. It represents the fighter who carries all before them, but also the seeker of high spiritual truth through hardship.",
    asDestinyNumber: "Your destiny is to fight for a cause, complete major cycles, and lead others through your courage.",
    asLifePath: "Your path involves learning to control your fiery nature and difficult early life. You are here to become a wise protector.",
    asSoulUrge: "Soul thrives on challenge and overcoming obstacles. Intense need for independence and to be the 'last one standing'.",
    asPersonality: "Appears as a forceful, determined, and sometimes impatient individual. Seen as a fearless fighter.",
    asBirthDay: "Strong will and determination. Prone to accidents but possesses incredible recovery power.",
    strengths: ["Courageous", "Determined", "Resilient", "Forceful"],
    challenges: ["Impulsive", "Quick-tempered", "Prone to accidents"],
    hiddenStrengths: ["High spiritual intuition", "Indomitable will"],
    careerPaths: ["Soldier", "Surgeon", "Athlete", "Firefighter", "Humanitarian"],
    careerNarrative: "Excels in high-stakes environments. They are fighters in everything they undertake and carry all before them.",
    relationshipPattern: "As self-assertive as they may seem, they need continual reassurance that they are liked — respected — admired — and loved. 10 is capable of arousing tl^ < extreme responses of love or hate — respect or fear. 10 is the symbol of LOve and Light, which create all that caajj be imagined, and also contains the code: Image 10 Ordaiiw Image it, and it shall be. It represents two members of the same or the opposite sex — or two | opposed situations. Pe- riodic changes in business and partnerships of all kinds are usually beneficial.",
    financialPattern: "Resourceful; gains through bold actions and risk-taking.",
    healthPattern: "Prone to fevers, inflammatory conditions, and sharp instruments.",
    compatibleWith: [1, 3, 5, 9],
    challengingWith: [2, 8],
    neutralWith: [4, 6, 7],
    luckyColors: [{ name: "Red", hex: "#FF0000", reason: "Mars fire" }, { name: "Crimson", hex: "#DC143C", reason: "Vitality" }],
    luckyDays: ["Tuesday", "Thursday", "Friday"],
    luckyGems: ["Ruby", "Coral", "Garnet"],
    luckyNumbers: [9, 18, 27],
    missingMeaning: "Lack of courage or drive; difficulty finishing projects or standing up for oneself.",
    missingImpact: { relationships: "Passive-aggression", career: "Quitting too easily", finances: "Fear of risk", dailyLife: "Weakness" },
    missingRemedy: { color: "Scarlet", habit: "Martial arts or intense exercise", name: "Add a 9 vibration", element: "Fire", timing: "Sunrise" },
    isGoodNumber: true,
    indaNarrative: "The Number 9 vibrates to the planet Mars. It represents ag- gressive action, penetration, courage, and conflict. 9 is the number of originality and initiative . . . also the .contradictory traits of vul- A person or entity is influenced by the Number 9 if born on the",
    historicalNote: "Known as the 'Sacred Number' that should not be reduced further in some traditions. Associated with Mars, the Greek God of War.",
    sunSignInteractions: {
      "Aries": "Intensifies Sun Sign traits.",
      "Scorpio": "Intensifies Sun Sign traits.",
      "Libra": "Opposes Sun Sign motives; requires effort to balance.",
      "Gemini": "Harmonizes well.",
      "Sagittarius": "Harmonizes well.",
      "Aquarius": "Harmonizes well.",
      "Capricorn": "Sharp contrast; behavior may startle others.",
      "Cancer": "Sharp contrast; behavior may startle others.",
      "Taurus": "Sharp contrast; behavior may startle others.",
      "Virgo": "Sharp contrast; behavior may startle others.",
      "Pisces": "Sharp contrast; behavior may startle others."
    }
  }
};
